SystemOrganization addCategory: #SpecUIAddOns!
SystemOrganization addCategory: 'SpecUIAddOns-Core'!
SystemOrganization addCategory: 'SpecUIAddOns-GrowableList'!
SystemOrganization addCategory: 'SpecUIAddOns-Lists'!
SystemOrganization addCategory: 'SpecUIAddOns-MorphicAdapters'!
SystemOrganization addCategory: 'SpecUIAddOns-Toolbars'!
SystemOrganization addCategory: 'SpecUIAddOns-Widgets'!
SystemOrganization addCategory: 'SpecUIAddOns-Wizard'!
